export const GET_POKEMONS = "http://localhost:3001/pokemons"
export const GET_DATA= "http://localhost:3001/pokemons/"
export const GET_NAME= "http://localhost:3001/pokemons?name="
export const GET_POKEMONSDB = "http://localhost:3001/pokemons/DB"
export const GET_POKEMONSAPI = "http://localhost:3001/pokemons/API"
export const GET_TYPE = "http://localhost:3001/type"